[character]
error_symbol = "[❯](bold #ff5555)"
success_symbol = "[❯](bold #50fa7b)"

[cmd_duration]
min_time = 50
format = 'took [$duration](bold yellow)'

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[python]
pyenv_version_name = true
